config/routes.rb
Rails.application.routes.draw do
  resources :facturas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/factura.rb
class Factura < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_action :set_factura, only: [:show, :edit, :update, :destroy]

  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.all
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
  end

  # GET /facturas/new
  def new
    @factura = Factura.new
  end

  # GET /facturas/1/edit
  def edit
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(factura_params)

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Factura was successfully created.' }
        format.json { render :show, status: :created, location: @factura }
      else
        format.html { render :new }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facturas/1
  # PATCH/PUT /facturas/1.json
  def update
    respond_to do |format|
      if @factura.update(factura_params)
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { render :show, status: :ok, location: @factura }
      else
        format.html { render :edit }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura.destroy
    respond_to do |format|
      format.html { redirect_to facturas_url, notice: 'Factura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factura
      @factura = Factura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factura_params
      params.require(:factura).permit(:Factura, :Fecha, :Proveedor, :Concepto, :Valor, :Estado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_form.html.erb
<%= form_with(model: factura, local: true) do |form| %>
  <% if factura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(factura.errors.count, "error") %> prohibited this factura from being saved:</h2>

      <ul>
      <% factura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="form-group">
    <%= form.label :Factura %>
    <div class="col-sm-6">
    <%= form.number_field :Factura, id: :factura_Factura %>
  </div>
  </div>

  <div class="form-group">
    <%= form.label :Fecha %>
    <div class="col-sm-6">
    <%= form.date_select :Fecha, id: :factura_Fecha %>
  </div>
</div>
  <div class="form-group">
    <%= form.label :Proveedor %>
    <div class="col-sm-6">
    <%= form.text_field :Proveedor, id: :factura_Proveedor %>
  </div>
</div>
  <div class="form-group">
    <%= form.label :Concepto %>
    <div class="col-sm-6">
    <%= form.text_field :Concepto, id: :factura_Concepto %>
  </div>
</div>
  <div class="form-group">
    <%= form.label :Valor %>
    <div class="col-sm-6">
    <%= form.text_field :Valor, id: :factura_Valor %>
  </div>
</div>
  <div class="form-group">
    <%= form.label :Estado %>
    <div class="col-sm-6">
    <%= form.text_field :Estado, id: :factura_Estado %>
  </div>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/facturas/edit.html.erb
<h1>Editing Factura</h1>

<%= render 'form', factura: @factura %>

<%= link_to 'Mostrar', @factura %> |
<%= link_to 'Regresar', facturas_path %>

app/views/facturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Facturas</h1>

<table>
  <thead>
    <tr>
      <th>Factura</th>
      <th>Fecha</th>
      <th>Proveedor</th>
      <th>Concepto</th>
      <th>Valor</th>
      <th>Estado</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @facturas.each do |factura| %>
      <tr>
        <td><%= factura.Factura %></td>
        <td><%= factura.Fecha %></td>
        <td><%= factura.Proveedor %></td>
        <td><%= factura.Concepto %></td>
        <td><%= factura.Valor %></td>
        <td><%= factura.Estado %></td>
        <td><%= link_to 'Show', factura %></td>
        <td><%= link_to 'Edit', edit_factura_path(factura) %></td>
        <td><%= link_to 'Destroy', factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar', new_factura_path %>

app/views/facturas/new.html.erb
<h1>New Factura</h1>

<%= render 'form', factura: @factura %>

<%= link_to 'Back', facturas_path %>

app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_factura_path(@factura) %> |
<%= link_to 'Back', facturas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>